- name: install tengine-server
  yum:
    name:
      - http://demo.jumpserver.org/download/centos/7/tengine-2.3.2-1.el7.ngx.x86_64.rpm
    state: present

- firewalld:
    zone: public
    port: "{{ http_port }}/tcp"
    permanent: yes
    immediate: yes
    state: enabled

- firewalld:
    zone: public
    port: "{{ https_port }}/tcp"
    permanent: yes
    immediate: yes
    state: enabled
  when:
    - https_port is defined

- firewalld:
    zone: public
    port: "{{ ssh_port }}/tcp"
    permanent: yes
    immediate: yes
    state: enabled

- shell: setenforce 0

- name: Disable SELinux
  selinux:
    state: disabled

- name: install nfs-utils
  yum:
    name:
      - nfs-utils
    state: present

- name: create nfs data directory
  file:
    path: "{{ nfs_dest_dir }}"
    state: directory
    mode: '0755'

- name: mount nfs data directory
  mount:
    fstype: nfs
    opts: rw
    src: "{{ groups['nfs'][0] }}:{{ nfs_src_dir }}"
    path: "{{ nfs_dest_dir }}"
    state: mounted

- name: download luna
  get_url:
    url: http://demo.jumpserver.org/download/luna/{{ jumpserver_version }}/luna.tar.gz
    dest: /opt/luna.tar.gz
  notify:
    - extract luna

- name: remove nginx default conf
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent

- name: copy nginx conf
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: nginx.conf.j2, dest: /etc/nginx/nginx.conf }
    - { src: jumpserver.conf.j2, dest: /etc/nginx/conf.d/jumpserver.conf }
  notify:
    - restart nginx
