---

- firewalld:
    zone: public
    port: "{{ http_port }}/tcp"
    permanent: yes
    immediate: yes
    state: enabled

- firewalld:
    zone: public
    port: "{{ https_port }}/tcp"
    permanent: yes
    immediate: yes
    state: enabled
  when:
    - https_port is defined

- firewalld:
    zone: public
    port: "{{ ssh_port }}/tcp"
    permanent: yes
    immediate: yes
    state: enabled

- shell: setenforce 0

- name: Disable SELinux
  selinux:
    state: disabled

- name: install nfs-utils
  yum:
    name:
      - nfs-utils
    state: present

- name: create nfs data directory
  file:
    path: "{{ nfs_dest_dir }}"
    state: directory
    mode: '0755'

- name: mount nfs data directory
  mount:
    fstype: nfs
    opts: rw
    src: "{{ nfs_server }}:{{ nfs_src_dir }}"
    path: "{{ nfs_dest_dir }}"
    state: mounted

- name: copy file to nginx
  copy:
    src: "{{ item }}"
    dest: "{{ install_dir }}/"
  loop:
    - "{{ downloads_dir }}/luna.tar.gz"
    - "{{ downloads_dir }}/{{ tengine_name }}"
  notify:
    - extract luna

- name: install tengine-server
  yum:
    name:
      - "{{ install_dir }}/{{ tengine_name }}"
    state: present

- name: remove nginx default conf
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent

- name: copy nginx conf
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: nginx.conf.j2, dest: /etc/nginx/nginx.conf }
    - { src: jumpserver.conf.j2, dest: /etc/nginx/conf.d/jumpserver.conf }
  notify:
    - restart nginx
