---

- name: install docker prepare
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - python2-pip
    state: present

- firewalld:
    rich_rule: 'rule family=ipv4 source address="{{ jms_network }}" port protocol=tcp port=8081 accept'
    permanent: yes
    state: enabled
    immediate: yes

- name: add docker repository
  yum_repository:
    name: docker-ce
    description: Docker CE Stable - $basearch
    baseurl: https://mirrors.aliyun.com/docker-ce/linux/centos/7/$basearch/stable
    gpgcheck: no
    enabled: 1
  notify: yum-clean-metadata

- name: install docker-ce
  yum:
    name:
      - docker-ce
    state: present

- name: create docker directories
  file:
    path: /etc/docker
    state: directory

- name: copy docker mirrors file
  copy:
    src: "{{ downloads_dir }}/{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: daemon.json, dest: /etc/docker/daemon.json }
  notify:
    - restart docker

- meta: flush_handlers

- name: enable docker automatic start
  systemd:
    name: docker
    state: started
    enabled: yes

- pip:
    name: docker-py
    extra_args: -i {{ pip_mirrors }}

- name: create guacamole container
  docker_container:
    name: jms_guacamole
    image: "jumpserver/jms_guacamole:{{ jms_version }}"
    state: started
    restart: yes
    recreate: yes
    ports:
      - "8081:8080"
    env:
      JUMPSERVER_KEY_DIR: "/config/guacamole/key"
      JUMPSERVER_SERVER: "http://{{ nginx_server }}"
      BOOTSTRAP_TOKEN: "{{ bootstrap_token }}"
