- name: install mariadb-server
  yum:
    name:
      - mariadb
      - mariadb-devel
      - mariadb-server
      - python2-PyMySQL
    state: present

- name: enable mariadb automatic start
  systemd:
    name: mariadb
    state: started
    enabled: yes

- firewalld:
    rich_rule: 'rule family=ipv4 source address="{{ jms_network }}" port protocol=tcp port=3306 accept'
    permanent: yes
    state: enabled
    immediate: yes

- name: remove anonymous user
  mysql_user:
    name: ''
    host_all: yes
    state: absent

- name: dalete database test
  mysql_db:
    name: test
    state: absent

- name: create database {{ db_name }}
  mysql_db:
    name: "{{ db_name }}"
    encoding: utf8

- name: create user {{ db_user }}
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_passwd }}"
    priv: "{{ db_name }}.*:ALL"
    host: "{{ db_host }}"
    state: present
