---

- name: install docker prepare
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - python2-pip
    state: present

- firewalld:
    rich_rule: 'rule family=ipv4 source address="{{ jms_network }}" port protocol=tcp port=2222 accept'
    permanent: yes
    state: enabled
    immediate: yes

- firewalld:
    rich_rule: 'rule family=ipv4 source address="{{ jms_network }}" port protocol=tcp port=5000 accept'
    permanent: yes
    state: enabled
    immediate: yes

- name: add docker repository
  yum_repository:
    name: docker-ce
    description: Docker CE Stable - $basearch
    baseurl: https://mirrors.aliyun.com/docker-ce/linux/centos/7/$basearch/stable
    gpgcheck: no
    enabled: 1
  notify: yum-clean-metadata

- name: install docker-ce
  yum:
    name:
      - docker-ce
    state: present

- name: create docker directories
  file:
    path: /etc/docker
    state: directory

- name: copy docker mirrors file
  copy:
    src: "{{ downloads_dir }}/{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: daemon.json, dest: /etc/docker/daemon.json }
  notify:
    - restart docker

- meta: flush_handlers

- name: enable docker automatic start
  systemd:
    name: docker
    state: started
    enabled: yes

- pip:
    name: docker-py
    extra_args: -i {{ pip_mirrors }}

- name: create koko container
  docker_container:
    name: jms_koko
    image: "jumpserver/jms_koko:{{ jms_version }}"
    state: started
    ports:
      - "2222:2222"
      - "5000:5000"
    env:
      CORE_HOST: "http://{{ nginx_server }}"
      BOOTSTRAP_TOKEN: "{{ bootstrap_token }}"
      REDIS_HOST: "{{ redis_host }}"
      REDIS_PORT: "6379"
      REDIS_PASSWORD: "{{ redis_passwd }}"
